---
:email:
  :user: username@example.com
  :password: password
  :to: somebody@example.com
  :cc: somebodyelse@example.com, andhisfriend@example.com
:twitter:
  :user: twitter_user
  :password: twitter_pass
:shift_type: "pc" # or xbox, or ps3
