---
:email:
  :user: username@example.com
  :password: password
  :to: somebody@example.com
  :cc: somebodyelse@example.com, andhisfriend@example.com
:twitter:
  :consumer_key: ''
  :consumer_secret: ''
  :oauth_token: ''
  :oauth_token_secret: ''
  :auth_method: :oauth
:shift_type: "pc" # or xbox, or ps3
